# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('stars', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('discription', models.CharField(max_length=1024)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rent', models.BigIntegerField()),
                ('negotiable', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rentals.Rental'),
        ),
    ]
