# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_reviews_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intrested_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviews_count',
        ),
    ]
