# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='discription',
            new_name='description',
        ),
    ]
