# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='intrested',
            field=models.ManyToManyField(blank=True, related_name='intrested_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
