# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20180124_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
