# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_intrested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='intrested',
            field=models.ManyToManyField(blank=True, related_name='intrested_rentals', to=settings.AUTH_USER_MODEL),
        ),
    ]
