# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
