# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20180308_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
