# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20180127_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='lon',
            new_name='lat',
        ),
    ]
