# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_auto_20180129_1459'),
        ('rentals', '0006_auto_20180127_1616'),
    ]

    operations = [
    ]
