# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_remove_rental_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='photo',
        ),
    ]
