# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_auto_20180211_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='pic',
            new_name='photo',
        ),
    ]
