# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_auto_20180212_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='rental',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
